steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - container_long/Dockerfile
      - -t
      - us-docker.pkg.dev/$PROJECT_ID/douyin/long-worker:test
      - .

images:
  - us-docker.pkg.dev/$PROJECT_ID/douyin/long-worker:test

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
timeout: 3600s
