steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - -f
      - container_long/Dockerfile.coordinator
      - -t
      - us-docker.pkg.dev/$PROJECT_ID/douyin/long-coordinator:prod
      - .

images:
  - us-docker.pkg.dev/$PROJECT_ID/douyin/long-coordinator:prod

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
timeout: 1800s
